name: Docs PR

on:
  pull_request:
    paths:
      - 'packages/docs/**'

defaults:
  run:
    working-directory: packages/docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
